services:
  - type: web
    name: candycraze-backend
    runtime: docker
    plan: free
    region: oregon
    branch: dev
    buildCommand: ""
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: MONGODB_URI
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: MONGODB_DATABASE
        value: candycraze
